dataset: "kitti"

n_relations: 4

enable_log: false
kitti_root: '/data/dataset/KITTI_Odometry_Semantic'
kitti_preprocess_root: '/data/dataset/kitti_semantic_preprocess'
kitti_logdir: '/OCTraN/logs/'

fp_loss: true 
frustum_size: 8 
batch_size: 1
n_gpus: 1
num_workers_per_gpu: 3 
exp_prefix: "exp"
run: 1
lr: 1e-4
weight_decay: 1e-4 

context_prior: true

relation_loss: true 
CE_ssc_loss: true
sem_scal_loss: true
geo_scal_loss: true

project_1_2: true
project_1_4: true
project_1_8: true